# Generated by Django 4.2.2 on 2023-06-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_banner_cartorder_cartorderitems_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
