# Generated by Django 4.2.2 on 2023-07-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
