# Generated by Django 4.2.2 on 2023-07-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Return Processing', 'Return Processing'), ('Returned', 'Returned')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('ReturnApproved', 'ReturnApproved')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
